"""add scans table

Revision ID: 90c4c39b3809
Revises: 8f2a5001926e
Create Date: 2026-04-10 03:25:07.734013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90c4c39b3809'
down_revision = '8f2a5001926e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scans',
    sa.Column('scan_id', sa.UUID(), nullable=False),
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('image_type', sa.Enum('ultrasound', 'mammogram', name='imagetype'), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('image_public_id', sa.String(length=300), nullable=False),
    sa.Column('prediction', sa.Enum('benign', 'malignant', 'normal', name='predictionclass'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('prob_benign', sa.Float(), nullable=False),
    sa.Column('prob_malignant', sa.Float(), nullable=False),
    sa.Column('prob_normal', sa.Float(), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('scan_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('scans')
    # ### end Alembic commands ###
